### ISSUE TITLE
Support for om client credentials

### ISSUE THREAD

**Issue by aegershman** [pivotal/hammer#15]
In order to support opsmanagers configured w/ SAML, LDAP, etc., which don't use basic auth & only support client credentials, it would be real nifty if `hammer` could support `--client-id (OM_CLIENT_ID)` and `--client-secret (OM_CLIENT_SECRET)` in lieu of username/password

Thanks for the consideration 👍

**Comment by edwardecook** [comment]
This is an interesting area that I hadn't really considered, what kind of config change do you think would make the most sense? 

The two main versions of this I can see would be 
```
{
  "ops_manager": {
    "url": "OPSMAN-FQDN",
    "username": "OPSMAN-CLIENT-ID",
    "password": "OPSMAN-CLIENT-PASSWORD",
    "client_credentials": true
  },
  ...
}
```
Where `ops_manager.client_credentials` would default to false or
```
{
  "ops_manager": {
    "url": "OPSMAN-FQDN",
    "client_id": "OPSMAN-CLIENT-ID",
    "client_password": "OPSMAN-CLIENT-PASSWORD"
  },
  ...
}
```
where it would default to using `ops_manager.username` and `ops_manager.password` if they were present.

I'll run this past a couple of people, do you have any particular preference or other thoughts?

**Comment by aegershman** [comment]
besides opsmgrs which don't have basic auth creds, the secondary use-case I'm thinking of (but haven't actively experimented with yet) for client creds is using `hammer` in the context of automation, where `hammer` would be used as a cleaner way to delegate commands to `pks`, `bosh`, `cf`, etc. within a reusable concourse task

---

that's a good question, I think I'm down for option 2, where you can specify either `client_id/client_secret` or `username/password`, _or_ if you specify both, it takes one or the other as default & ignores the other?

For example [it looks like `pivotal-cf/om` will accept client-id/secret and username/password](https://github.com/pivotal-cf/om/blob/master/main.go#L107) and when it creates the oauth client it takes [`client-id/secret` as precedence if provided, and username/password as secondary](https://github.com/pivotal-cf/om/blob/master/network/oauth_client.go#L95-L104)

I feel the same thing applies with `hammer`, but instead hammer use username/password as the "primary" preferable choice in case both client-id/secret and username/password are provided

... so tl;dr, second choice _feels_ right; if you can run it by some other people and get their opinions that'd probably be real helpful 👍

**Comment by gmrodgers** [comment]
I think the second choice would be my preferred option as well.  Although I'd argue for the default to be the `client_id/client_secret` to be the default so that it is consistent with `om`.  I think `hammer` is early enough in its life to make this switch.
