### ISSUE TITLE
Namespace "TARGET_ENVIRONMENT_CONFIG" env var with "HAMMER_"

### ISSUE THREAD

**Issue by aegershman** [pivotal/hammer#17]
In order to ensure the env value which sets `hammer`'s `TARGET_ENVIRONMENT_CONFIG` is clearly marked for use with `hammer`, consider renaming `TARGET_ENVIRONMENT_CONFIG` to something such as `HAMMER_TARGET_CONFIG`

Examples:`CREDHUB_SERVER` is used in `credhub login`, `BOSH_ENVIRONMENT` for `bosh` cli, etc.

---

This is a super minor thing, I'm just logging it because the idea came to me but it's obviously non-essential. Feel free to close whenever 👍

**Comment by edwardecook** [comment]
Thanks for the suggestion, makes a lot of sense to me. I think given this is all pre v1 there shouldn't be any issue with a breaking change of this kind.

I haven't had much time to work on hammer in the past few days but I'll try and carve out some time towards the start of next week.
