### ISSUE TITLE
Ability to leverage YAML rather than JSON for hammer targets

### ISSUE THREAD

**Issue by aegershman** [pivotal/hammer#18]
I realize everyone on the Internet hates YAML, _but_, it may be less trouble on the eyes for a human to configure a `hammer` target which is stored in `YAML` than `JSON`.

---

This is a super minor thing, it's non-essential & cosmetic. Only logging it because it came to me as an idea.  Obviously feel free to close whenever. No hard feelings if/when closed with a simple "nah" 👍

**Comment by edwardecook** [comment]
I'll double check but this might be a relatively simple switch, I'll see what it looks like. As before not necessarily going to have a chance to work on this before next week.
