### ISSUE TITLE
Unclear why "ops_manager_public_ip" is required for envs with FQDNs

### ISSUE THREAD

**Issue by aegershman** [pivotal/hammer#19]
The [doc shows that an environment file should (in general) look like this](https://github.com/pivotal/hammer#config):

```json
{
  "name": "ENVIRONMENT-NAME",
  "ops_manager": {
    "url": "OPSMAN-FQDN",
    "username": "OPSMAN-USERNAME",
    "password": "OPSMAN-PASSWORD"
  },
  "ops_manager_private_key": "OPSMAN-RSA-PRIVATE-KEY",
  "ops_manager_public_ip": "OPSMAN-PUBLIC-IP",
  "sys_domain": "PAS-SYSTEM-DOMAIN",
  "pks_api":  {
     "url": "PKS-API-FQDN"
  }
}
```

The key `ops_manager_public_ip` appears to be required for commands, but it's not necessarily _used_ for those commands.

Currently our opsmgr envs all have FQDNs attached to them, which is supplied as part of `ops_manager.url`, but irrelevant to `ops_manager_public_ip`, which is requesting an non-empty IP string... So currently I just put in "0.0.0.0" and the value is satisfied/appears to be ignored, but it's a bit peculiar why it's required for commands when the `ops_manager.url` is what's actually used.

---

Again, not a massive problem, just logging it as a backlog item. Thanks for the time and consideration; I might be missing something, or it's just more convenience to leave it there as a param? Regardless, feel free to close this whenever 👍

**Comment by edwardecook** [comment]
So for the most part you're right there are a couple of instances where the public ip is used directly:
* in the bosh runner for configuring ssh gateway
* in the om runner for configuring an ssh command

I completely agree that it is essentially duplicate information when we have the FQDN, the only wrinkle is making sure that the command used to determine ip from uri is sufficiently universal and present on both macs and linux.
