### ISSUE TITLE
PKS Login should be supported

### ISSUE THREAD

**Issue by dherbrich** [pivotal/hammer#39]
The hammer file normally contains all information to do the PKS login. This should be implemented to make the tool more convenient to use for PKS envs.

**Comment by gmrodgers** [comment]
Hey @dherbrich 
I'm assuming you mean logging into the PKS API?  If so, this was released in [v0.6.0](https://github.com/pivotal/hammer/releases/tag/v0.6.0), via the `hammer pks-login` command.
Hope this helps

**Comment by dherbrich** [comment]
thank you. i missed that since i was still on some weird dev build from some month ago. (i thought i had updated recently)
