### ISSUE TITLE
Feature Request: Please set three new environment variables for `hammer bosh` command.

### ISSUE THREAD

**Issue by Houlistonm** [pivotal/hammer#9]
We are experiencing an issue with the bosh-cli (https://github.com/cloudfoundry/bosh-cli/issues/328) during the following command

`hammer bosh -- -d cf-c965095e0afd2591daab ssh clock_global/52145b71-4b6a-44ba-8d46-d4361328f085`

ssh returns 
```
Running SSH:
  1 error occurred:
        * Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/home/ec2-user/.bosh/tmp/ssh-priv-key750669365 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/home/ec2-user/.bosh/tmp/ssh-known-hosts168026640 -o ProxyCommand=nc -x 127.0.0.1:39601 %!h(MISSING) %!p(MISSING) 10.2.32.10 -l bosh_7542b2ed9bb54c8', stdout: '', stderr: '': exit status 255
```

Our work around is to set three new environment variables:
```bash
eval "$(hammer bosh)"
echo "export BOSH_GW_HOST=$( grep -Po '(?<=@)([^:]+)(?=:)' <<< $BOSH_ALL_PROXY )"
echo "export BOSH_GW_USER=$( grep -Po '(?<=://)([^@]+)(?=@)' <<< $BOSH_ALL_PROXY )"
echo "export BOSH_GW_PRIVATE_KEY=$( grep -Po '(?<=key=)(.*)' <<< $BOSH_ALL_PROXY )"
```
and then succesfully ssh to a vm with the following command.
```bash
hammer bosh -- -d cf-c965095e0afd2591daab ssh clock_global/52145b71-4b6a-44ba-8d46-d4361328f085 --gw-socks5=
```

The feature request is for the 'hammer bosh ...' command to set and/or output those three env variables depending on the command invocation.

**Comment by edwardecook** [comment]
With the work for #10 (via #11) merged in this should be done, thanks again for the contributions!

I'll cut a release with this work later today.

**Comment by edwardecook** [comment]
Release: https://github.com/pivotal/hammer/releases/tag/v0.5.0
